# Generated by Django 4.1.4 on 2022-12-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_source_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.GenericIPAddressField(unique=True)),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
