# Generated by Django 4.1.4 on 2022-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_ipmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmodel',
            name='ipAddress',
            field=models.GenericIPAddressField(),
        ),
    ]
